INSERT IGNORE INTO department (id, name) VALUES (1, "First"),
       (2, "Second"),
       (3, "Third"),
       (4, "Fourth"),
       (5, "Fifth"),
       (6, "Sixth"),
       (7, "Seventh"),
       (8, "Eighth"),
       (9, "Ninth"),
       (10, "Tenth");